import React from 'react';
import type { Metadata } from 'next';

import TanstackQueryProvider from '@/contexts/TanstackQueryProvider';

import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body>
      <TanstackQueryProvider>{children}</TanstackQueryProvider>
    </body>
  </html>
);

export default RootLayout;
