name: Tests suit

on: [pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build project
        run: bun install -y && bun run build
      - name: Unit tests
        run: bun run jest:run
      - name: Cypress App tests
        uses: cypress-io/github-action@v2
        with:
          start: bun run start
          wait-on: http://localhost:3000
          browser: chrome
          config: baseUrl=http://localhost:3000,integrationFolder=cypress/integration,testFiles=**/*.*
      - name: Cypress Storybook tests
        uses: cypress-io/github-action@v2
        with:
          start: bun run storybook:start
          wait-on: http://localhost:6006
          browser: chrome
          config: baseUrl=http://localhost:6006,integrationFolder=playground,testFiles=**/*.e2e.*

